### ISSUE TITLE
We noticed you added mocha as a dependency but we see no tests

### ISSUE THREAD

**Issue by danielsan** [yorodm/currency#2]
Would you mind writing some tests?

**Comment by yorodm** [comment]
Hello:

I'm not familiar enough with JavaScript testing frameworks yet. I made an attempt to use mocha but I was reaching the end line. Will work on some tests and add them

**Comment by danielsan** [comment]
Hey man,
Do we have any updates on this issue?

Here is one of our Opensource projects with a few tests using Mocha, Chai, and Sinon
https://github.com/EveryMundo/aws-kinesis-client

**Comment by yorodm** [comment]
Hi Daniel:
Thanks for the link, it will help me a lot. Sadly my PC died last week(power surge) and I'm still getting the parts to bring it back to life. Will keep you posted on this issue and update the code ASAP.

**Comment by yorodm** [comment]
Hi @danielsan:

Added test using `mocha' and `supertest'. In the future I need to figure out a better way to use mocha to do **actual** unit testing instead of integration tests but I'm working on borrowed time and this method of testing keeps popping everywhere I look.
